// Code generated by protoc-gen-go. DO NOT EDIT.
// source: boomerCall.proto

package boomerCall

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type InitBommerRequest struct {
	IsSession            bool                             `protobuf:"varint,1,opt,name=isSession,proto3" json:"isSession,omitempty"`
	PreTask              []*InitBommerRequest_HttpRequest `protobuf:"bytes,2,rep,name=PreTask,proto3" json:"PreTask,omitempty"`
	MainTask             []*InitBommerRequest_TestTask    `protobuf:"bytes,3,rep,name=MainTask,proto3" json:"MainTask,omitempty"`
	LocustMaster         string                           `protobuf:"bytes,4,opt,name=LocustMaster,proto3" json:"LocustMaster,omitempty"`
	HttpProxy            string                           `protobuf:"bytes,5,opt,name=HttpProxy,proto3" json:"HttpProxy,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *InitBommerRequest) Reset()         { *m = InitBommerRequest{} }
func (m *InitBommerRequest) String() string { return proto.CompactTextString(m) }
func (*InitBommerRequest) ProtoMessage()    {}
func (*InitBommerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c72101129612ec0, []int{0}
}

func (m *InitBommerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitBommerRequest.Unmarshal(m, b)
}
func (m *InitBommerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitBommerRequest.Marshal(b, m, deterministic)
}
func (m *InitBommerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitBommerRequest.Merge(m, src)
}
func (m *InitBommerRequest) XXX_Size() int {
	return xxx_messageInfo_InitBommerRequest.Size(m)
}
func (m *InitBommerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InitBommerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InitBommerRequest proto.InternalMessageInfo

func (m *InitBommerRequest) GetIsSession() bool {
	if m != nil {
		return m.IsSession
	}
	return false
}

func (m *InitBommerRequest) GetPreTask() []*InitBommerRequest_HttpRequest {
	if m != nil {
		return m.PreTask
	}
	return nil
}

func (m *InitBommerRequest) GetMainTask() []*InitBommerRequest_TestTask {
	if m != nil {
		return m.MainTask
	}
	return nil
}

func (m *InitBommerRequest) GetLocustMaster() string {
	if m != nil {
		return m.LocustMaster
	}
	return ""
}

func (m *InitBommerRequest) GetHttpProxy() string {
	if m != nil {
		return m.HttpProxy
	}
	return ""
}

type InitBommerRequest_SaveParamAction struct {
	SaveType             int32    `protobuf:"varint,1,opt,name=SaveType,proto3" json:"SaveType,omitempty"`
	ParamName            string   `protobuf:"bytes,2,opt,name=ParamName,proto3" json:"ParamName,omitempty"`
	RuleValue            string   `protobuf:"bytes,3,opt,name=RuleValue,proto3" json:"RuleValue,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitBommerRequest_SaveParamAction) Reset()         { *m = InitBommerRequest_SaveParamAction{} }
func (m *InitBommerRequest_SaveParamAction) String() string { return proto.CompactTextString(m) }
func (*InitBommerRequest_SaveParamAction) ProtoMessage()    {}
func (*InitBommerRequest_SaveParamAction) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c72101129612ec0, []int{0, 0}
}

func (m *InitBommerRequest_SaveParamAction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitBommerRequest_SaveParamAction.Unmarshal(m, b)
}
func (m *InitBommerRequest_SaveParamAction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitBommerRequest_SaveParamAction.Marshal(b, m, deterministic)
}
func (m *InitBommerRequest_SaveParamAction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitBommerRequest_SaveParamAction.Merge(m, src)
}
func (m *InitBommerRequest_SaveParamAction) XXX_Size() int {
	return xxx_messageInfo_InitBommerRequest_SaveParamAction.Size(m)
}
func (m *InitBommerRequest_SaveParamAction) XXX_DiscardUnknown() {
	xxx_messageInfo_InitBommerRequest_SaveParamAction.DiscardUnknown(m)
}

var xxx_messageInfo_InitBommerRequest_SaveParamAction proto.InternalMessageInfo

func (m *InitBommerRequest_SaveParamAction) GetSaveType() int32 {
	if m != nil {
		return m.SaveType
	}
	return 0
}

func (m *InitBommerRequest_SaveParamAction) GetParamName() string {
	if m != nil {
		return m.ParamName
	}
	return ""
}

func (m *InitBommerRequest_SaveParamAction) GetRuleValue() string {
	if m != nil {
		return m.RuleValue
	}
	return ""
}

type InitBommerRequest_AssertAction struct {
	AssertType           int32    `protobuf:"varint,1,opt,name=AssertType,proto3" json:"AssertType,omitempty"`
	RuleValue            int32    `protobuf:"varint,2,opt,name=RuleValue,proto3" json:"RuleValue,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitBommerRequest_AssertAction) Reset()         { *m = InitBommerRequest_AssertAction{} }
func (m *InitBommerRequest_AssertAction) String() string { return proto.CompactTextString(m) }
func (*InitBommerRequest_AssertAction) ProtoMessage()    {}
func (*InitBommerRequest_AssertAction) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c72101129612ec0, []int{0, 1}
}

func (m *InitBommerRequest_AssertAction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitBommerRequest_AssertAction.Unmarshal(m, b)
}
func (m *InitBommerRequest_AssertAction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitBommerRequest_AssertAction.Marshal(b, m, deterministic)
}
func (m *InitBommerRequest_AssertAction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitBommerRequest_AssertAction.Merge(m, src)
}
func (m *InitBommerRequest_AssertAction) XXX_Size() int {
	return xxx_messageInfo_InitBommerRequest_AssertAction.Size(m)
}
func (m *InitBommerRequest_AssertAction) XXX_DiscardUnknown() {
	xxx_messageInfo_InitBommerRequest_AssertAction.DiscardUnknown(m)
}

var xxx_messageInfo_InitBommerRequest_AssertAction proto.InternalMessageInfo

func (m *InitBommerRequest_AssertAction) GetAssertType() int32 {
	if m != nil {
		return m.AssertType
	}
	return 0
}

func (m *InitBommerRequest_AssertAction) GetRuleValue() int32 {
	if m != nil {
		return m.RuleValue
	}
	return 0
}

type InitBommerRequest_HttpRequest struct {
	UrlPath              string                               `protobuf:"bytes,1,opt,name=UrlPath,proto3" json:"UrlPath,omitempty"`
	Method               string                               `protobuf:"bytes,2,opt,name=Method,proto3" json:"Method,omitempty"`
	Headers              map[string]string                    `protobuf:"bytes,3,rep,name=Headers,proto3" json:"Headers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	DictData             map[string]string                    `protobuf:"bytes,4,rep,name=DictData,proto3" json:"DictData,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Params               map[string]string                    `protobuf:"bytes,5,rep,name=Params,proto3" json:"Params,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	RawData              string                               `protobuf:"bytes,6,opt,name=RawData,proto3" json:"RawData,omitempty"`
	JsonData             string                               `protobuf:"bytes,7,opt,name=JsonData,proto3" json:"JsonData,omitempty"`
	SaveParamChain       []*InitBommerRequest_SaveParamAction `protobuf:"bytes,8,rep,name=SaveParamChain,proto3" json:"SaveParamChain,omitempty"`
	AssertChain          []*InitBommerRequest_AssertAction    `protobuf:"bytes,9,rep,name=AssertChain,proto3" json:"AssertChain,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                             `json:"-"`
	XXX_unrecognized     []byte                               `json:"-"`
	XXX_sizecache        int32                                `json:"-"`
}

func (m *InitBommerRequest_HttpRequest) Reset()         { *m = InitBommerRequest_HttpRequest{} }
func (m *InitBommerRequest_HttpRequest) String() string { return proto.CompactTextString(m) }
func (*InitBommerRequest_HttpRequest) ProtoMessage()    {}
func (*InitBommerRequest_HttpRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c72101129612ec0, []int{0, 2}
}

func (m *InitBommerRequest_HttpRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitBommerRequest_HttpRequest.Unmarshal(m, b)
}
func (m *InitBommerRequest_HttpRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitBommerRequest_HttpRequest.Marshal(b, m, deterministic)
}
func (m *InitBommerRequest_HttpRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitBommerRequest_HttpRequest.Merge(m, src)
}
func (m *InitBommerRequest_HttpRequest) XXX_Size() int {
	return xxx_messageInfo_InitBommerRequest_HttpRequest.Size(m)
}
func (m *InitBommerRequest_HttpRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InitBommerRequest_HttpRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InitBommerRequest_HttpRequest proto.InternalMessageInfo

func (m *InitBommerRequest_HttpRequest) GetUrlPath() string {
	if m != nil {
		return m.UrlPath
	}
	return ""
}

func (m *InitBommerRequest_HttpRequest) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *InitBommerRequest_HttpRequest) GetHeaders() map[string]string {
	if m != nil {
		return m.Headers
	}
	return nil
}

func (m *InitBommerRequest_HttpRequest) GetDictData() map[string]string {
	if m != nil {
		return m.DictData
	}
	return nil
}

func (m *InitBommerRequest_HttpRequest) GetParams() map[string]string {
	if m != nil {
		return m.Params
	}
	return nil
}

func (m *InitBommerRequest_HttpRequest) GetRawData() string {
	if m != nil {
		return m.RawData
	}
	return ""
}

func (m *InitBommerRequest_HttpRequest) GetJsonData() string {
	if m != nil {
		return m.JsonData
	}
	return ""
}

func (m *InitBommerRequest_HttpRequest) GetSaveParamChain() []*InitBommerRequest_SaveParamAction {
	if m != nil {
		return m.SaveParamChain
	}
	return nil
}

func (m *InitBommerRequest_HttpRequest) GetAssertChain() []*InitBommerRequest_AssertAction {
	if m != nil {
		return m.AssertChain
	}
	return nil
}

type InitBommerRequest_TestTask struct {
	TaskName             string                           `protobuf:"bytes,1,opt,name=TaskName,proto3" json:"TaskName,omitempty"`
	TaskWeight           int32                            `protobuf:"varint,2,opt,name=TaskWeight,proto3" json:"TaskWeight,omitempty"`
	PreWork              []*InitBommerRequest_HttpRequest `protobuf:"bytes,3,rep,name=PreWork,proto3" json:"PreWork,omitempty"`
	TestWork             *InitBommerRequest_HttpRequest   `protobuf:"bytes,4,opt,name=TestWork,proto3" json:"TestWork,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *InitBommerRequest_TestTask) Reset()         { *m = InitBommerRequest_TestTask{} }
func (m *InitBommerRequest_TestTask) String() string { return proto.CompactTextString(m) }
func (*InitBommerRequest_TestTask) ProtoMessage()    {}
func (*InitBommerRequest_TestTask) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c72101129612ec0, []int{0, 3}
}

func (m *InitBommerRequest_TestTask) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitBommerRequest_TestTask.Unmarshal(m, b)
}
func (m *InitBommerRequest_TestTask) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitBommerRequest_TestTask.Marshal(b, m, deterministic)
}
func (m *InitBommerRequest_TestTask) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitBommerRequest_TestTask.Merge(m, src)
}
func (m *InitBommerRequest_TestTask) XXX_Size() int {
	return xxx_messageInfo_InitBommerRequest_TestTask.Size(m)
}
func (m *InitBommerRequest_TestTask) XXX_DiscardUnknown() {
	xxx_messageInfo_InitBommerRequest_TestTask.DiscardUnknown(m)
}

var xxx_messageInfo_InitBommerRequest_TestTask proto.InternalMessageInfo

func (m *InitBommerRequest_TestTask) GetTaskName() string {
	if m != nil {
		return m.TaskName
	}
	return ""
}

func (m *InitBommerRequest_TestTask) GetTaskWeight() int32 {
	if m != nil {
		return m.TaskWeight
	}
	return 0
}

func (m *InitBommerRequest_TestTask) GetPreWork() []*InitBommerRequest_HttpRequest {
	if m != nil {
		return m.PreWork
	}
	return nil
}

func (m *InitBommerRequest_TestTask) GetTestWork() *InitBommerRequest_HttpRequest {
	if m != nil {
		return m.TestWork
	}
	return nil
}

type EndBommerRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EndBommerRequest) Reset()         { *m = EndBommerRequest{} }
func (m *EndBommerRequest) String() string { return proto.CompactTextString(m) }
func (*EndBommerRequest) ProtoMessage()    {}
func (*EndBommerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c72101129612ec0, []int{1}
}

func (m *EndBommerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EndBommerRequest.Unmarshal(m, b)
}
func (m *EndBommerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EndBommerRequest.Marshal(b, m, deterministic)
}
func (m *EndBommerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EndBommerRequest.Merge(m, src)
}
func (m *EndBommerRequest) XXX_Size() int {
	return xxx_messageInfo_EndBommerRequest.Size(m)
}
func (m *EndBommerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EndBommerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EndBommerRequest proto.InternalMessageInfo

type BoomerCallResponse struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BoomerCallResponse) Reset()         { *m = BoomerCallResponse{} }
func (m *BoomerCallResponse) String() string { return proto.CompactTextString(m) }
func (*BoomerCallResponse) ProtoMessage()    {}
func (*BoomerCallResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c72101129612ec0, []int{2}
}

func (m *BoomerCallResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BoomerCallResponse.Unmarshal(m, b)
}
func (m *BoomerCallResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BoomerCallResponse.Marshal(b, m, deterministic)
}
func (m *BoomerCallResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BoomerCallResponse.Merge(m, src)
}
func (m *BoomerCallResponse) XXX_Size() int {
	return xxx_messageInfo_BoomerCallResponse.Size(m)
}
func (m *BoomerCallResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BoomerCallResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BoomerCallResponse proto.InternalMessageInfo

func (m *BoomerCallResponse) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *BoomerCallResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*InitBommerRequest)(nil), "InitBommerRequest")
	proto.RegisterType((*InitBommerRequest_SaveParamAction)(nil), "InitBommerRequest.SaveParamAction")
	proto.RegisterType((*InitBommerRequest_AssertAction)(nil), "InitBommerRequest.AssertAction")
	proto.RegisterType((*InitBommerRequest_HttpRequest)(nil), "InitBommerRequest.HttpRequest")
	proto.RegisterMapType((map[string]string)(nil), "InitBommerRequest.HttpRequest.DictDataEntry")
	proto.RegisterMapType((map[string]string)(nil), "InitBommerRequest.HttpRequest.HeadersEntry")
	proto.RegisterMapType((map[string]string)(nil), "InitBommerRequest.HttpRequest.ParamsEntry")
	proto.RegisterType((*InitBommerRequest_TestTask)(nil), "InitBommerRequest.TestTask")
	proto.RegisterType((*EndBommerRequest)(nil), "EndBommerRequest")
	proto.RegisterType((*BoomerCallResponse)(nil), "BoomerCallResponse")
}

func init() { proto.RegisterFile("boomerCall.proto", fileDescriptor_3c72101129612ec0) }

var fileDescriptor_3c72101129612ec0 = []byte{
	// 620 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0x5d, 0x4f, 0x13, 0x41,
	0x14, 0xb5, 0x2d, 0xfd, 0xd8, 0xdb, 0x8a, 0x30, 0x1a, 0xb3, 0x59, 0x0d, 0x92, 0x7d, 0x22, 0x6a,
	0xf6, 0x01, 0x63, 0x40, 0x78, 0xa2, 0x80, 0x41, 0x02, 0xa6, 0x19, 0x50, 0x12, 0xdf, 0x86, 0x72,
	0x43, 0x37, 0x74, 0x77, 0xea, 0xcc, 0x14, 0xed, 0xb3, 0xcf, 0xfe, 0x23, 0x7f, 0x93, 0xbf, 0xc1,
	0xcc, 0xc7, 0x4e, 0xb7, 0x80, 0x56, 0x9e, 0x76, 0xee, 0x9d, 0x73, 0xce, 0xdc, 0x3d, 0x73, 0xe7,
	0xc2, 0xd2, 0x39, 0xe7, 0x19, 0x8a, 0x5d, 0x36, 0x1c, 0x26, 0x23, 0xc1, 0x15, 0x8f, 0x7f, 0x07,
	0xb0, 0xfc, 0x21, 0x4f, 0x55, 0x97, 0x67, 0x19, 0x0a, 0x8a, 0x5f, 0xc7, 0x28, 0x15, 0x79, 0x0e,
	0x41, 0x2a, 0x4f, 0x50, 0xca, 0x94, 0xe7, 0x61, 0x65, 0xb5, 0xb2, 0xd6, 0xa2, 0xd3, 0x04, 0xd9,
	0x84, 0x66, 0x4f, 0xe0, 0x29, 0x93, 0x57, 0x61, 0x75, 0xb5, 0xb6, 0xd6, 0x5e, 0x5f, 0x49, 0x6e,
	0x49, 0x24, 0x07, 0x4a, 0x8d, 0xdc, 0x9a, 0x16, 0x70, 0xb2, 0x01, 0xad, 0x63, 0x96, 0xe6, 0x86,
	0x5a, 0x33, 0xd4, 0x67, 0x77, 0x50, 0x4f, 0x51, 0x2a, 0x0d, 0xa1, 0x1e, 0x4c, 0x62, 0xe8, 0x1c,
	0xf1, 0xfe, 0x58, 0xaa, 0x63, 0x26, 0x15, 0x8a, 0x70, 0x61, 0xb5, 0xb2, 0x16, 0xd0, 0x99, 0x9c,
	0x2e, 0x5a, 0x1f, 0xda, 0x13, 0xfc, 0xfb, 0x24, 0xac, 0x1b, 0xc0, 0x34, 0x11, 0xa5, 0xf0, 0xe8,
	0x84, 0x5d, 0x63, 0x8f, 0x09, 0x96, 0xed, 0xf4, 0x95, 0xfe, 0x8f, 0x08, 0x5a, 0x3a, 0x75, 0x3a,
	0x19, 0xa1, 0xf9, 0xc9, 0x3a, 0xf5, 0xb1, 0x16, 0x33, 0xd0, 0x8f, 0x2c, 0xc3, 0xb0, 0x6a, 0xc5,
	0x7c, 0x42, 0xef, 0xd2, 0xf1, 0x10, 0x3f, 0xb3, 0xe1, 0x18, 0xc3, 0x9a, 0xdd, 0xf5, 0x89, 0xe8,
	0x08, 0x3a, 0x3b, 0x52, 0xa2, 0x50, 0xee, 0x9c, 0x15, 0x00, 0x1b, 0x97, 0x4e, 0x2a, 0x65, 0x66,
	0xd5, 0xaa, 0x66, 0xbb, 0xa4, 0xf6, 0xb3, 0x0e, 0xed, 0x92, 0x99, 0x24, 0x84, 0xe6, 0x27, 0x31,
	0xec, 0x31, 0x35, 0x30, 0x52, 0x01, 0x2d, 0x42, 0xf2, 0x14, 0x1a, 0xc7, 0xa8, 0x06, 0xfc, 0xc2,
	0x15, 0xec, 0x22, 0xb2, 0x0f, 0xcd, 0x03, 0x64, 0x17, 0x28, 0xa4, 0x33, 0xfd, 0xd5, 0xbf, 0xef,
	0x2b, 0x71, 0xe8, 0xfd, 0x5c, 0x89, 0x09, 0x2d, 0xb8, 0xe4, 0x00, 0x5a, 0x7b, 0x69, 0x5f, 0xed,
	0x31, 0xc5, 0xc2, 0x05, 0xa3, 0xf3, 0x7a, 0x8e, 0x4e, 0x01, 0xb7, 0x42, 0x9e, 0x4d, 0xba, 0xd0,
	0x30, 0x5e, 0xca, 0xb0, 0x6e, 0x74, 0x5e, 0xce, 0xd1, 0xb1, 0x60, 0xab, 0xe2, 0x98, 0xda, 0x06,
	0xca, 0xbe, 0x99, 0x62, 0x1a, 0xd6, 0x06, 0x17, 0xea, 0x6b, 0x3d, 0x94, 0x3c, 0x37, 0x5b, 0x4d,
	0xb3, 0xe5, 0x63, 0x72, 0x08, 0x8b, 0xbe, 0x0b, 0x76, 0x07, 0x2c, 0xcd, 0xc3, 0x96, 0xa9, 0x20,
	0xbe, 0xa3, 0x82, 0x1b, 0xed, 0x42, 0x6f, 0x30, 0xc9, 0x0e, 0xb4, 0xed, 0x25, 0x5a, 0xa1, 0xc0,
	0x08, 0xbd, 0xb8, 0x43, 0xa8, 0xdc, 0x0c, 0xb4, 0xcc, 0x89, 0xb6, 0xa0, 0x53, 0xf6, 0x9a, 0x2c,
	0x41, 0xed, 0x0a, 0x27, 0xee, 0x5e, 0xf5, 0x92, 0x3c, 0x81, 0xfa, 0xb5, 0xef, 0x8b, 0x80, 0xda,
	0x60, 0xab, 0xba, 0x59, 0x89, 0xb6, 0xe1, 0xe1, 0x8c, 0xbf, 0xf7, 0x22, 0xbf, 0x83, 0x76, 0xc9,
	0xd4, 0x7b, 0x51, 0x7f, 0x55, 0xa0, 0x55, 0xbc, 0x50, 0xed, 0xb5, 0xfe, 0x9a, 0x57, 0x62, 0xd9,
	0x3e, 0xd6, 0x6d, 0xaf, 0xd7, 0x67, 0x98, 0x5e, 0x0e, 0x94, 0xeb, 0xeb, 0x52, 0xc6, 0x8d, 0x91,
	0x33, 0x2e, 0x8a, 0x59, 0xf0, 0x3f, 0x63, 0x44, 0xc3, 0xc9, 0x96, 0xad, 0xc0, 0x50, 0xf5, 0x24,
	0x98, 0x4f, 0xf5, 0xf8, 0x98, 0xc0, 0xd2, 0x7e, 0x7e, 0x31, 0x83, 0x8c, 0xdf, 0x03, 0xe9, 0xfa,
	0xc1, 0x48, 0x51, 0x8e, 0x78, 0x2e, 0x51, 0x3f, 0x27, 0xa9, 0x98, 0x1a, 0x4b, 0x37, 0x01, 0x5d,
	0xa4, 0x3b, 0x2f, 0x43, 0x29, 0xd9, 0x65, 0x61, 0x4e, 0x11, 0xae, 0xff, 0xa8, 0xc0, 0xf2, 0x54,
	0xe8, 0x04, 0xc5, 0x75, 0xda, 0x47, 0xb2, 0x01, 0x30, 0x2d, 0x8e, 0x90, 0xdb, 0x95, 0x46, 0x8f,
	0x93, 0xdb, 0xc7, 0xc7, 0x0f, 0xc8, 0x5b, 0x08, 0x7c, 0xa9, 0x64, 0x39, 0xb9, 0x59, 0xf6, 0x5f,
	0x68, 0xdd, 0xc5, 0x2f, 0x9d, 0x64, 0x7b, 0x3a, 0xe8, 0xcf, 0x1b, 0x66, 0xd2, 0xbf, 0xf9, 0x13,
	0x00, 0x00, 0xff, 0xff, 0x68, 0x68, 0x30, 0xbc, 0xfd, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BoomerCallServiceClient is the client API for BoomerCallService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BoomerCallServiceClient interface {
	InitBommer(ctx context.Context, in *InitBommerRequest, opts ...grpc.CallOption) (*BoomerCallResponse, error)
	EndBommer(ctx context.Context, in *EndBommerRequest, opts ...grpc.CallOption) (*BoomerCallResponse, error)
}

type boomerCallServiceClient struct {
	cc *grpc.ClientConn
}

func NewBoomerCallServiceClient(cc *grpc.ClientConn) BoomerCallServiceClient {
	return &boomerCallServiceClient{cc}
}

func (c *boomerCallServiceClient) InitBommer(ctx context.Context, in *InitBommerRequest, opts ...grpc.CallOption) (*BoomerCallResponse, error) {
	out := new(BoomerCallResponse)
	err := c.cc.Invoke(ctx, "/BoomerCallService/InitBommer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *boomerCallServiceClient) EndBommer(ctx context.Context, in *EndBommerRequest, opts ...grpc.CallOption) (*BoomerCallResponse, error) {
	out := new(BoomerCallResponse)
	err := c.cc.Invoke(ctx, "/BoomerCallService/EndBommer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BoomerCallServiceServer is the server API for BoomerCallService service.
type BoomerCallServiceServer interface {
	InitBommer(context.Context, *InitBommerRequest) (*BoomerCallResponse, error)
	EndBommer(context.Context, *EndBommerRequest) (*BoomerCallResponse, error)
}

// UnimplementedBoomerCallServiceServer can be embedded to have forward compatible implementations.
type UnimplementedBoomerCallServiceServer struct {
}

func (*UnimplementedBoomerCallServiceServer) InitBommer(ctx context.Context, req *InitBommerRequest) (*BoomerCallResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitBommer not implemented")
}
func (*UnimplementedBoomerCallServiceServer) EndBommer(ctx context.Context, req *EndBommerRequest) (*BoomerCallResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EndBommer not implemented")
}

func RegisterBoomerCallServiceServer(s *grpc.Server, srv BoomerCallServiceServer) {
	s.RegisterService(&_BoomerCallService_serviceDesc, srv)
}

func _BoomerCallService_InitBommer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitBommerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoomerCallServiceServer).InitBommer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/BoomerCallService/InitBommer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoomerCallServiceServer).InitBommer(ctx, req.(*InitBommerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BoomerCallService_EndBommer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EndBommerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoomerCallServiceServer).EndBommer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/BoomerCallService/EndBommer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoomerCallServiceServer).EndBommer(ctx, req.(*EndBommerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BoomerCallService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "BoomerCallService",
	HandlerType: (*BoomerCallServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InitBommer",
			Handler:    _BoomerCallService_InitBommer_Handler,
		},
		{
			MethodName: "EndBommer",
			Handler:    _BoomerCallService_EndBommer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "boomerCall.proto",
}
